apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  clusterIP: None
