apiVersion: v1
kind: Service
metadata:
  name: keycloak-http
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/auth/metrics"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 8443
    targetPort: https
