apiVersion: v1
kind: Service
metadata:
  name: keycloak-http
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: keycloak-x
    app.kubernetes.io/name: keycloakx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: https
    protocol: TCP
    port: 8443
    targetPort: https
