apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: keycloak
        app.kubernetes.io/name: keycloak
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      serviceAccountName: keycloak
      enableServiceLinks: true
      containers:
      - name: keycloak
        image: "quay.io/keycloak/keycloak:19.0.3"
        command:
        - "/opt/keycloak/bin/kc.sh"
        - "--verbose start"
        args: []
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        - name: https
          protocol: TCP
          containerPort: 8443
        envFrom: []
        env:
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HTTP_RELATIVE_PATH
          value: /auth
        - name: KC_CACHE
          value: "ispn"
        - name: KC_CACHE_STACK
          value: "kubernetes"
        - name: KC_PROXY
          value: edge
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_LOG_LEVEL
          value: "INFO,org.infinispan:INFO,org.jgroups:INFO"
        - name: JAVA_OPTS_APPEND
          value: -Djgroups.dns.query=keycloak-headless
        - name: JAVA_TOOL_OPTIONS
          value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
        resources: {}
        volumeMounts:
        livenessProbe:
          httpGet:
            port: http
            path: '/auth/'
          initialDelaySeconds: 0
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            port: http
            path: '/auth/realms/master'
          initialDelaySeconds: 10
          timeoutSeconds: 1
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        startupProbe:
          failureThreshold: 60
          httpGet:
            port: http
            path: '/auth/'
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 1
      volumes:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: NotIn
                  values:
                  - test
                matchLabels:
                  app.kubernetes.io/instance: keycloak
                  app.kubernetes.io/name: keycloak
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: NotIn
                values:
                - test
              matchLabels:
                app.kubernetes.io/instance: keycloak
                app.kubernetes.io/name: keycloak
            topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 1000
  serviceName: keycloak-headless
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
