apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
configMapGenerator:
- name: keycloak-properies
  envs:
  - .env
configurations:
- configuration/sealed-secret-config.yaml
generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/envFrom"
      value:
      - configMapRef:
          name: keycloak-properies
      - secretRef:
          name: keycloak-secrets
  target:
    name: keycloak
    kind: StatefulSet
secretGenerator:
- name: keycloak-secrets
  envs:
  - .env.secret
