namespace: dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
- name: keycloak
  count: 2
resources:
- ../../base
- namespace.yaml
configMapGenerator:
- name: keycloak-properies
  envs:
  - .env
patches:
- path: env-patch.yaml
  target:
    name: keycloak
    kind: StatefulSet
secretGenerator:
- name: keycloak-secrets
  envs:
  - .env.secret
