apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- persistent-volume.yaml
bases:
- ../../base
configurations:
- configuration/sealed-secret-config.yaml
generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
secretGenerator:
- name: postgres-secrets
  envs:
  - .env.secret
