apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

secretGenerator:
- name: postgres-secrets
  envs:
  - .env.secret

configurations:
  - configuration/sealed-secret-config.yaml

generatorOptions:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"

resources:
  - persistent-volume.yaml