apiVersion: v1
data:
  POSTGRES_PASSWORD: c29tZV9wYXNzd29yZA==
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: postgres-secrets
type: Opaque