apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres

commonLabels:
  app.kubernetes.io/name: postgresql
  app.kubernetes.io/instance: postgres
  app.kubernetes.io/component: primary

resources:
  - statefulset.yaml
  - service-hl.yaml
  - service.yaml