apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres
resources:
- statefulset.yaml
- service-hl.yaml
- service.yaml
- persistent-volume.yaml
commonLabels:
  app.kubernetes.io/component: primary
  app.kubernetes.io/instance: postgres
  app.kubernetes.io/name: postgresql
