apiVersion: v1
kind: Service
metadata:
  name: postgres-postgresql
  namespace: "default"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql
  ports:
  - name: tcp-postgresql
    port: 5432
    targetPort: tcp-postgresql
    nodePort: null
  sessionAffinity: None
