apiVersion: v1
kind: Service
metadata:
  name: mailhog
  labels:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.0.1"
  namespace: default
spec:
  type: "ClusterIP"
  ports:
    - name: http
      port: 8025
      protocol: TCP
      targetPort: http
    - name: tcp-smtp
      port: 1025
      protocol: TCP
      targetPort: tcp-smtp
  selector:
    app.kubernetes.io/name: mailhog
    app.kubernetes.io/instance: release-name
