apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
  download_dashboards.sh: |
    #!/usr/bin/env sh
    set -euf

    curl -skf \
    --connect-timeout 60 \
    --max-time 60 \
    -H "Accept: application/json" \
    -H "Content-Type: application/json;charset=UTF-8" \
      "https://grafana.com/api/dashboards/14390/revisions/2/download" \
      | sed '/-- .* --/! s/"datasource":.*,/"datasource": "Prometheus",/g' \
    > "/var/lib/grafana/dashboards/default/prometheus-stats.json"
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - access: proxy
        jsonData:
          httpMethod: POST
          prometheusType: Prometheus
          prometheusVersion: 2.39.1
        name: Prometheus
        type: prometheus
        url: http://prometheus.monitoring.svc.cluster.local