apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv0002/
  storageClassName: standard