apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-volume
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv0003/
    type: Directory
  storageClassName: standard